// 快照的 skills 根：repository（= 快照目录名）→ 上游放 SKILL.md 的相对子路径。
// provider 的 customSkillDirs、test/packaging.test.mjs 的反查路径、test/persona.test.mjs 的
// files 登记都从这里取，所以"第三颗快照的 skill 不在 <repo>/skills/"这种结构差异只需要改一处。
// 上游目录结构本身不动（见 docs/dev/selected-skills.md §8.6）。
export const SELECTED_SKILL_SKILL_DIRS = Object.freeze({
  'investment-skills': 'skills',
  'china-stock-research-skills': 'skills',
  InvestSkill: 'plugins/us-stock-analysis/skills',
  // 上游把 SKILL.md 放在仓库根，快照因此套了一层 skills/<name>/（理由见该快照的 UPSTREAM.md）。
  'peter-lynch-skill': 'skills',
})

// Selected-skill metadata owned by Capital Generation. Upstream snapshots remain unchanged.
// 能力标签的词表就是下面 SELECTED_SKILL_TAG_LABELS 的键：卡片按条目实际用到的标签现算筛选条，
// 少一套语言的显示名就会露出英文原词（test/capital-config.test.mjs 钉着）。
export const SELECTED_SKILL_CATALOG = Object.freeze([
  {
    key: 'buffettFramework',
    name: 'buffett-investment-framework',
    label: { zh: 'Buffett Investment Framework', en: 'Buffett Investment Framework' },
    description: {
      zh: '以证据为基础的商业质量、资本配置、估值和风险分析框架。主要源于美股语境。',
      en: 'Evidence-led business quality, capital allocation, valuation, and risk analysis. Primarily US-market oriented.',
    },
    owner: 'finterm-ai',
    repository: 'investment-skills',
    status: 'experimental',
    lastCommit: '2026-07-22',
    reviewBy: '2026-11-06',
    tags: ['business-analysis', 'cash-flow', 'perspective', 'risk', 'valuation'],
    riskNote: {
      zh: '实验性质；不能直接当作 A 股规则或投资建议。',
      en: 'Experimental; do not treat it as A-share rules or investment advice.',
    },
  },
  {
    key: 'financialHealth',
    name: 'financial-health',
    label: { zh: '财务健康', en: 'Financial Health' },
    description: {
      zh: '检查盈利质量、现金转换、营运资本、杠杆和资产负债表风险。',
      en: 'Checks earnings quality, cash conversion, working capital, leverage, and balance-sheet risk.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'cash-flow', 'financial-health', 'risk'],
    riskNote: {
      zh: '冷启动实验；上游维护较久未更新，启用前请自行复核内容和来源。',
      en: 'Cold-start experiment; upstream has been quiet, so review content and sources before use.',
    },
  },
  {
    key: 'riskWarningCatalysts',
    name: 'risk-warning-catalysts',
    label: { zh: '风险与催化剂监控', en: 'Risk Warning Catalysts' },
    description: {
      zh: '把研究结论转成带来源、阈值和复查频率的风险与催化剂监控项。',
      en: 'Turns research into source-backed risk and catalyst monitoring with thresholds and review cadence.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'monitoring', 'risk'],
    riskNote: {
      zh: '冷启动实验；不负责估值或交易决策。',
      en: 'Cold-start experiment; it does not make valuation or trading decisions.',
    },
  },
  {
    key: 'valuationInvestmentStrategy',
    name: 'valuation-investment-strategy',
    label: { zh: '估值与情景分析', en: 'Valuation Investment Strategy' },
    description: {
      zh: '在事实基础完成后构建带假设、情景和失效条件的估值框架。',
      en: 'Builds valuation scenarios with assumptions and invalidation conditions after the factual base is ready.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'risk', 'valuation'],
    riskNote: {
      zh: '冷启动实验；输出不等于买卖或仓位建议。',
      en: 'Cold-start experiment; output is not a buy, sell, or position-size recommendation.',
    },
  },
  {
    key: 'strategyBusinessTransition',
    name: 'strategy-business-transition',
    label: { zh: '战略与业务转型', en: 'Strategy Business Transition' },
    description: {
      zh: '检验公司战略叙事、业务迁移、资本配置和转型里程碑。',
      en: 'Tests strategy narratives, business migration, capital allocation, and transition milestones.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'strategy', 'risk'],
    riskNote: {
      zh: '冷启动实验；不负责估值或交易计划。',
      en: 'Cold-start experiment; it does not make valuation or trading plans.',
    },
  },
  {
    key: 'industryCompetitionMoat',
    name: 'industry-competition-moat',
    label: { zh: '行业竞争与护城河', en: 'Industry Competition Moat' },
    description: {
      zh: '分析行业结构、竞争格局、供需和公司差异化是否可持续。',
      en: 'Analyzes industry structure, competition, supply-demand, and sustainable differentiation.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'business-analysis', 'competition', 'risk'],
    riskNote: {
      zh: '冷启动实验；行业判断仍需回到公开证据。',
      en: 'Cold-start experiment; industry conclusions still require public evidence.',
    },
  },
  {
    key: 'businessDecompositionOrderQuality',
    name: 'business-decomposition-order-quality',
    label: { zh: '业务拆解与订单质量', en: 'Business Decomposition Order Quality' },
    description: {
      zh: '拆解产品、客户、项目和订单，检查增长能否转化为收入和现金。',
      en: 'Breaks down products, customers, projects, and orders to test conversion into revenue and cash.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'business-analysis', 'cash-flow', 'orders', 'risk'],
    riskNote: {
      zh: '冷启动实验；不负责最终估值或买卖建议。',
      en: 'Cold-start experiment; it does not make final valuation or trading recommendations.',
    },
  },
  {
    key: 'tenKDigest',
    name: '10k-digest',
    label: { zh: '年报（10-K）逐节精读', en: '10-K Report Digest' },
    description: {
      zh: '逐节精读美股年报 10-K，产出摘要、分节要点、关键指标与可核对的出处引用。',
      en: 'Reads a 10-K section by section into an abstract, section summaries, key metrics and sourced references.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'filings', 'business-analysis'],
    riskNote: {
      zh: '实验性质；章节口径按美股 10-K 写，A 股年报的披露结构不同，不能直接平移。',
      en: 'Experimental; the section map follows US 10-K disclosure and does not transfer to A-share annual reports.',
    },
  },
  {
    key: 'bearCase',
    name: 'bear-case',
    label: { zh: '空头视角红队反驳', en: 'Bear Case Red Team' },
    description: {
      zh: '针对一个看多论点刻意构建最强的反面论证，逐条找出反证与脆弱假设。',
      en: 'Builds the strongest deliberate short-side counter-argument to a bullish thesis, with counterevidence.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'risk', 'perspective'],
    riskNote: {
      zh: '实验性质；只做反面论证，不构成卖出或做空建议，也不预测跌幅。',
      en: 'Experimental; a counter-argument only, not a sell or short recommendation and no downside forecast.',
    },
  },
  {
    key: 'catalystCalendar',
    name: 'catalyst-calendar',
    label: { zh: '90 天催化剂日历', en: 'Catalyst Calendar' },
    description: {
      zh: '列出未来 90 天的事件催化剂与预期影响，用来安排复查节奏。',
      en: 'Lists upcoming catalysts over a 90-day window with expected impact and a review cadence.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'earnings', 'monitoring'],
    riskNote: {
      zh: '实验性质；事件影响是定性判断，不预测具体涨跌。',
      en: 'Experimental; catalyst impact is qualitative and does not forecast price moves.',
    },
  },
  {
    key: 'competitorAnalysis',
    name: 'competitor-analysis',
    label: { zh: '直接对手与护城河', en: 'Competitor Analysis' },
    description: {
      zh: '围绕一家公司与其直接对手做护城河、市场地位与行业格局分析。',
      en: 'Moat, market position and industry dynamics for one company against its direct rivals.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'competition', 'business-analysis', 'risk'],
    riskNote: {
      zh: '与「行业竞争与护城河」视角重叠，同业名单与口径按美股披露取材；结论仍要回到公开证据。',
      en: 'Overlaps the industry/moat lens; peer sets follow US disclosure, so conclusions still need public evidence.',
    },
  },
  {
    key: 'dividendAnalysis',
    name: 'dividend-analysis',
    label: { zh: '分红回购与资本配置', en: 'Dividend & Capital Allocation' },
    description: {
      zh: '把分红、回购、并购、债务管理与自由现金流去向合起来看资本配置纪律。',
      en: 'Reviews dividends, buybacks, M&A, debt and FCF deployment as one capital-allocation discipline.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'capital-allocation', 'cash-flow', 'valuation'],
    riskNote: {
      zh: '实验性质；不承诺股息可持续性，也不预测收益。',
      en: 'Experimental; it does not promise dividend sustainability or returns.',
    },
  },
  {
    key: 'earningsCallAnalysis',
    name: 'earnings-call-analysis',
    label: { zh: '业绩电话会文本分析', en: 'Earnings Call Analysis' },
    description: {
      zh: '从业绩电话会纪要里读情绪、主题与管理层口径的变化。',
      en: 'Reads sentiment, themes and shifts in management tone from earnings call transcripts.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'earnings', 'perspective'],
    riskNote: {
      zh: '必须先拿到纪要原文；没有原文时不许凭印象补写管理层表态。',
      en: 'Needs the actual transcript; never reconstruct management remarks from memory.',
    },
  },
  {
    key: 'earningsPreview',
    name: 'earnings-preview',
    label: { zh: '财报前三档情景推演', en: 'Earnings Preview' },
    description: {
      zh: '对比一致预期与期权隐含波动，给出超预期/符合/不及三档情景与各自要盯的指标。',
      en: 'Compares consensus with the implied move and lays out beat / in-line / miss scenarios with watch KPIs.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'earnings', 'risk', 'monitoring'],
    riskNote: {
      zh: '实验性质；正文每档情景带仓位写法，只当推演练习，不是交易指令。',
      en: 'Experimental; each scenario carries position wording — read it as a rehearsal, not a trade instruction.',
    },
  },
  {
    key: 'economicsAnalysis',
    name: 'economics-analysis',
    label: { zh: '美国宏观指标解读', en: 'US Economics Analysis' },
    description: {
      zh: '解读美国宏观数据与利率路径，并交代它传导到市场的路径。',
      en: 'Interprets US macro prints and the rate path, and spells out the transmission to markets.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'macro', 'risk'],
    riskNote: {
      zh: '口径是美国宏观，对 A 股只能当外部环境变量，不直接推政策。',
      en: 'US macro only; for A-shares treat it as an external condition, not a policy read.',
    },
  },
  {
    key: 'etfAnalysis',
    name: 'etf-analysis',
    label: { zh: 'ETF 尽调与契合度评分', en: 'ETF Analysis' },
    description: {
      zh: '费率、跟踪误差、流动性、成分集中度与持仓重叠，汇成一枚 ETF 契合度评分。',
      en: 'Expense ratio, tracking difference, liquidity, concentration and overlap rolled into a fitness score.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'instruments', 'portfolio', 'risk'],
    riskNote: {
      zh: '实验性质；评分衡量结构特征，不代表收益预期。',
      en: 'Experimental; the score describes structure, not expected return.',
    },
  },
  {
    key: 'factCheck',
    name: 'fact-check',
    label: { zh: '逐条主张核验与补引用', en: 'Fact Check' },
    description: {
      zh: '把报告里的每个数字与事实主张拆出来逐条比对一手来源，标注已核验/不符/无法核验并回填引用。',
      en: 'Extracts every figure and claim, checks each against a primary source, and marks verified / mismatch / unverifiable.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'filings', 'verification'],
    riskNote: {
      zh: '一手来源清单按 SEC 文件、公司 IR、FRED 与交易所数据写；A 股材料要换成公告与官方披露。',
      en: 'Its primary-source list is SEC / IR / FRED / exchange data; swap in announcements and official disclosure for A-shares.',
    },
  },
  {
    key: 'financialReportAnalyst',
    name: 'financial-report-analyst',
    label: { zh: '财报质量与红旗解读', en: 'Financial Report Analyst' },
    description: {
      zh: '从 10-K / 10-Q 读报表质量、异常红旗与一个可交代出处的信号。',
      en: 'Reads statement quality, red flags and one sourced signal from 10-K / 10-Q filings.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'filings', 'financial-health', 'risk'],
    riskNote: {
      zh: '实验性质；红旗是提示复查的线索，不是结论。',
      en: 'Experimental; red flags are prompts to re-check, not conclusions.',
    },
  },
  {
    key: 'industryMap',
    name: 'industry-map',
    label: { zh: '产业链地图与咽喉点', en: 'Industry Map' },
    description: {
      zh: '把上下游画成有向图，定位公司位置、找供需瓶颈与利润池，并派生二线线索。',
      en: 'Maps the value chain as a directed graph to locate the company, find chokepoints and second-order ideas.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'macro', 'competition', 'business-analysis'],
    riskNote: {
      zh: '实验性质；产业链判断仍需逐条回到公开证据。',
      en: 'Experimental; value-chain reads still need claim-by-claim public evidence.',
    },
  },
  {
    key: 'insiderTrading',
    name: 'insider-trading',
    label: { zh: '内部人增减持追踪', en: 'Insider Trading' },
    description: {
      zh: '从 SEC Form 4 追踪高管与董事的增减变动并做解读。',
      en: 'Tracks executive and director buying and selling from SEC Form 4 filings.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'filings', 'monitoring', 'perspective'],
    riskNote: {
      zh: '依赖美国内部人申报制度；A 股要换成大股东与董监高变动公告，口径不可直接平移。',
      en: 'Assumes US insider filings; A-shares need major-holder and director-change announcements instead.',
    },
  },
  {
    key: 'institutionalOwnership',
    name: 'institutional-ownership',
    label: { zh: '机构持仓变动', en: 'Institutional Ownership' },
    description: {
      zh: '从 13F 文件读机构持仓变化，识别机构资金的迁移方向。',
      en: 'Reads changes in institutional holdings from 13F filings to spot where the money is moving.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'filings', 'monitoring'],
    riskNote: {
      zh: '13F 有一个季度滞后且不含空头仓位；读成趋势之前先记住这两点。',
      en: '13F lags a quarter and omits shorts — remember both before reading it as a trend.',
    },
  },
  {
    key: 'learningCoach',
    name: 'learning-coach',
    label: { zh: '把分析讲成课程', en: 'Learning Coach' },
    description: {
      zh: '像导师一样逐指标解释一份分析结果，再反问 3–5 个检验理解的问题。',
      en: 'Explains an analysis metric by metric in plain words, then asks 3–5 Socratic questions.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['education', 'perspective'],
    riskNote: {
      zh: '教学性质；它解释的是上游分析的口径，不额外产生投资判断。',
      en: 'Educational; it explains the analysis it is handed and forms no investment view of its own.',
    },
  },
  {
    key: 'optionsAnalysis',
    name: 'options-analysis',
    label: { zh: '期权希腊字母与隐波', en: 'Options Analysis' },
    description: {
      zh: '看希腊字母、隐含波动率与策略适配度，用来理解期权的风险形状。',
      en: 'Reviews Greeks, implied volatility and strategy fit to characterise an options risk shape.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'instruments', 'risk'],
    riskNote: {
      zh: '实验性质；只解释期权风险，不推荐具体合约或策略组合。',
      en: 'Experimental; it explains options risk and does not recommend contracts or spreads.',
    },
  },
  {
    key: 'portfolioReview',
    name: 'portfolio-review',
    label: { zh: '组合表现与配置偏离', en: 'Portfolio Review' },
    description: {
      zh: '复盘组合的收益来源、集中度与配置偏离，并列出需要盯的观察项。',
      en: 'Reviews portfolio performance, concentration and allocation drift, with items to watch.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'portfolio', 'risk'],
    riskNote: {
      zh: '与本插件自带的组合复盘流程重叠；这条按美股语境给观察清单，仓位动作仍由使用者决定。',
      en: 'Overlaps the built-in portfolio review; this one gives a US-context watchlist and leaves position moves to you.',
    },
  },
  {
    key: 'positionLadder',
    name: 'position-ladder',
    label: { zh: '分批建仓与摊薄节奏', en: 'Position Ladder' },
    description: {
      zh: '把建仓拆成分批的股数上下限与加减仓节奏，并检查批次记账、洗售窗口与总收益口径。',
      en: 'Plans a staged entry with share-count floors and ceilings, trim/re-add cadence, lot and wash-sale checks.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'portfolio', 'monitoring'],
    riskNote: {
      zh: '正文里的股数区间是推演用的练习，不是买卖指令；本插件不提供投资建议，仓位决定在使用者。',
      en: 'Its share-count ranges are rehearsal arithmetic, not orders; this plugin gives no investment advice.',
    },
  },
  {
    key: 'resultValidator',
    name: 'result-validator',
    label: { zh: '分析结果置信度评分', en: 'Result Validator' },
    description: {
      zh: '从数据质量、方法一致性与信号冲突三个维度，给一份分析结果打置信度分。',
      en: 'Scores an analysis\'s confidence across data quality, methodology and signal consistency.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['verification', 'perspective'],
    riskNote: {
      zh: '打的是数据与方法自洽度，不等于预测准确率，也不承诺表现。',
      en: 'It grades internal data/method consistency, not forecast accuracy or future performance.',
    },
  },
  {
    key: 'riskStressTest',
    name: 'risk-stress-test',
    label: { zh: '组合压力测试与风险预算', en: 'Risk Stress Test' },
    description: {
      zh: 'beta 加权敞口、历史情景重放、VaR / CVaR、最大回撤估计与流动性退出天数。',
      en: 'Beta-weighted exposure, historical scenario replay, VaR / CVaR, drawdown estimates and days to exit.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'portfolio', 'risk', 'macro'],
    riskNote: {
      zh: '模型化估计，假设一变结果就变；不构成风控额度，也不是减仓指令。',
      en: 'Model output moves with every assumption; this is not a risk limit or a de-risking order.',
    },
  },
  {
    key: 'sectorAnalysis',
    name: 'sector-analysis',
    label: { zh: '板块相对强弱与轮动', en: 'Sector Analysis' },
    description: {
      zh: '看美国各板块的相对强弱与轮动线索，并交代判断依据。',
      en: 'Reviews US sector positioning and rotation clues, and states what each read rests on.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'macro', 'competition'],
    riskNote: {
      zh: '板块分类按美股口径，与 A 股行业分类不可直接对照。',
      en: 'Sector taxonomy is US-market; it does not line up with A-share industry classification.',
    },
  },
  {
    key: 'shortInterest',
    name: 'short-interest',
    label: { zh: '空头持仓与挤压条件', en: 'Short Interest' },
    description: {
      zh: '读空头比例、回补成本与挤压条件，并检查利空堆积信号。',
      en: 'Analyses short ratio, cost to cover, squeeze conditions and bearish positioning signals.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'filings', 'monitoring', 'risk'],
    riskNote: {
      zh: '空头数据是滞后披露；当成实时结论之前先核对口径与截止日期。',
      en: 'Short data is reported with a lag — check basis and as-of date before reading it as live.',
    },
  },
  {
    key: 'stockEval',
    name: 'stock-eval',
    label: { zh: '基本面与估值综合评估', en: 'Stock Evaluation' },
    description: {
      zh: '把财务质量、成长、估值与风险合到一次综合评估里，并输出一个可交代出处的结论。',
      en: 'Combines quality, growth, valuation and risk into one evaluation with a sourced conclusion.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'business-analysis', 'financial-health', 'valuation', 'risk'],
    riskNote: {
      zh: '上游已把 fundamental-analysis 合入本条；综合结论仍是美股口径，不替代本插件既有研究流程。',
      en: 'Upstream folded fundamental-analysis in; the read is US-context and does not replace Capital\'s own research flow.',
    },
  },
  {
    key: 'stockScreener',
    name: 'stock-screener',
    label: { zh: '多标的横向打分排序', en: 'Stock Screener' },
    description: {
      zh: '按估值、质量、动量、情绪与成长五个维度给一篮子标的打分并排序。',
      en: 'Screens and ranks a list of US stocks across valuation, quality, momentum, sentiment and growth.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'valuation', 'business-analysis', 'technicals'],
    riskNote: {
      zh: '排序只反映当期打分口径，不预测未来表现；标的清单与数据来源仍要走本插件的取数链路。',
      en: 'Ranking reflects the current scoring inputs only, not future performance; data still comes via Capital\'s own sources.',
    },
  },
  {
    key: 'stockValuation',
    name: 'stock-valuation',
    label: { zh: '四方法估值区间', en: 'Stock Valuation' },
    description: {
      zh: 'DCF、可比公司、EV 倍数与剩余收益一起出估值区间，并逐条交代假设。',
      en: 'Values a company with DCF, comparables, EV multiples and residual income, stating every assumption.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'valuation', 'cash-flow'],
    riskNote: {
      zh: '区间随假设大幅移动；输出不等于目标价，也不是买卖建议。',
      en: 'Ranges swing with assumptions; the output is not a price target or a trade call.',
    },
  },
  {
    key: 'taxLens',
    name: 'tax-lens',
    label: { zh: '美国税务视角检视清单', en: 'Tax Lens' },
    description: {
      zh: '长短期资本利得、洗售窗口、合格股息持有期、批次选择与年度税负拖累的检视清单。',
      en: 'Checks short vs. long-term gains, wash-sale windows, qualified dividends, lot selection and estimated tax drag.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'tax', 'portfolio'],
    riskNote: {
      zh: '只讲美国税制且止于教育口径；中国大陆的税务与账户安排请咨询专业人士。',
      en: 'US tax mechanics, educational only; get professional advice for mainland-China tax and account matters.',
    },
  },
  {
    key: 'technicalAnalysis',
    name: 'technical-analysis',
    label: { zh: '技术面与指标解读', en: 'Technical Analysis' },
    description: {
      zh: '用均线、成交量、RSI / MACD 等指标读趋势、关键价位与复查触发条件。',
      en: 'Reads trend and key levels with moving averages, volume, RSI and MACD, plus re-check triggers.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'technicals', 'monitoring'],
    riskNote: {
      zh: '技术信号只给复查条件，不预测方向；不要把图形结论写成事实。',
      en: 'Technical signals are re-check triggers, not direction forecasts — do not present them as facts.',
    },
  },
  {
    key: 'thesisTracker',
    name: 'thesis-tracker',
    label: { zh: '投资论点存档与复核', en: 'Thesis Tracker' },
    description: {
      zh: '写下论点的 KPI、失效条件与催化剂，之后按新数据复查并给出维持 / 走弱 / 失效。',
      en: 'Records KPIs, invalidation triggers and catalysts, then re-checks them as INTACT / WEAKENED / BROKEN.',
    },
    owner: 'yennanliu',
    repository: 'InvestSkill',
    status: 'experimental',
    lastCommit: '2026-09-25',
    reviewBy: '2026-11-06',
    tags: ['us-stock', 'verification', 'monitoring', 'perspective'],
    riskNote: {
      zh: '上游假设能把论点落盘；在本插件下文件写在工作目录并服从当前会话权限。',
      en: 'Upstream assumes it can save files; under Capital it writes into the session workspace and obeys its permissions.',
    },
  },
  {
    key: 'peterLynchResearch',
    name: 'peter-lynch-skill',
    label: { zh: '彼得·林奇式个股研究', en: 'Peter Lynch Research' },
    description: {
      zh: '给一个代码或公司名，走快筛（SKIP / WATCHLIST / DEEP RESEARCH）或完整尽调，生意理解、分类与估值放在同一套检查里，每条主张配可点开的来源链接。美股与境外上市口径。',
      en: 'Screens a ticker or company fast (SKIP / WATCHLIST / DEEP RESEARCH) or runs full due diligence, with linked sources under every claim. US and overseas-listing conventions.',
    },
    owner: 'DjNero11',
    repository: 'peter-lynch-skill',
    status: 'watchlist',
    lastCommit: '2026-06-28',
    reviewBy: '2026-11-06',
    tags: ['peter-lynch', 'us-stock', 'valuation', 'risk', 'verification'],
    riskNote: {
      zh: '冷启动实验；上游仅两次提交、自 2026-06-28 起无更新，启用前请自行复核来源。X/10 衡量的是论点自洽度与结构特征，不预测表现，也不构成买卖建议。',
      en: 'Cold-start experiment; upstream has two commits and has been quiet since 2026-06-28, so review the sources before use. The X/10 score rates thesis consistency and structure, not forecast performance, and is not investment advice.',
    },
  },
])

export const SELECTED_SKILL_TAG_LABELS = Object.freeze({
  zh: {
    all: '全部',
    'a-share': 'A 股',
    'business-analysis': '业务分析',
    'capital-allocation': '资本配置',
    'cash-flow': '现金流',
    competition: '竞争格局',
    earnings: '业绩与电话会',
    education: '教学',
    filings: '披露文件',
    'financial-health': '财务健康',
    instruments: '期权与基金',
    macro: '宏观与行业',
    monitoring: '监控',
    orders: '订单',
    perspective: '分析视角',
    'peter-lynch': '彼得·林奇',
    portfolio: '组合与仓位',
    risk: '风险',
    strategy: '战略',
    tax: '税务',
    technicals: '技术面',
    'us-stock': '美股',
    valuation: '估值',
    verification: '证据核验',
  },
  en: {
    all: 'All',
    'a-share': 'A-share',
    'business-analysis': 'Business analysis',
    'capital-allocation': 'Capital allocation',
    'cash-flow': 'Cash flow',
    competition: 'Competition',
    earnings: 'Earnings',
    education: 'Education',
    filings: 'Filings',
    'financial-health': 'Financial health',
    instruments: 'Options & funds',
    macro: 'Macro & industry',
    monitoring: 'Monitoring',
    orders: 'Orders',
    perspective: 'Perspective',
    'peter-lynch': 'Peter Lynch',
    portfolio: 'Portfolio',
    risk: 'Risk',
    strategy: 'Strategy',
    tax: 'Tax',
    technicals: 'Technicals',
    'us-stock': 'US equity',
    valuation: 'Valuation',
    verification: 'Verification',
  },
})
