// Selected-skill metadata owned by Capital Generation. Upstream snapshots remain unchanged.
// 能力标签的词表就是下面 SELECTED_SKILL_TAG_LABELS 的键：卡片按条目实际用到的标签现算筛选条，
// 少一套语言的显示名就会露出英文原词（test/capital-config.test.mjs 钉着）。
export const SELECTED_SKILL_CATALOG = Object.freeze([
  {
    key: 'buffettFramework',
    name: 'buffett-investment-framework',
    label: { zh: 'Buffett Investment Framework', en: 'Buffett Investment Framework' },
    description: {
      zh: '以证据为基础的商业质量、资本配置、估值和风险分析框架。主要源于美股语境。',
      en: 'Evidence-led business quality, capital allocation, valuation, and risk analysis. Primarily US-market oriented.',
    },
    owner: 'finterm-ai',
    repository: 'investment-skills',
    status: 'experimental',
    lastCommit: '2026-07-22',
    reviewBy: '2026-11-06',
    tags: ['business-analysis', 'cash-flow', 'perspective', 'risk', 'valuation'],
    riskNote: {
      zh: '实验性质；不能直接当作 A 股规则或投资建议。',
      en: 'Experimental; do not treat it as A-share rules or investment advice.',
    },
  },
  {
    key: 'financialHealth',
    name: 'financial-health',
    label: { zh: '财务健康', en: 'Financial Health' },
    description: {
      zh: '检查盈利质量、现金转换、营运资本、杠杆和资产负债表风险。',
      en: 'Checks earnings quality, cash conversion, working capital, leverage, and balance-sheet risk.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'cash-flow', 'financial-health', 'risk'],
    riskNote: {
      zh: '冷启动实验；上游维护较久未更新，启用前请自行复核内容和来源。',
      en: 'Cold-start experiment; upstream has been quiet, so review content and sources before use.',
    },
  },
  {
    key: 'riskWarningCatalysts',
    name: 'risk-warning-catalysts',
    label: { zh: '风险与催化剂监控', en: 'Risk Warning Catalysts' },
    description: {
      zh: '把研究结论转成带来源、阈值和复查频率的风险与催化剂监控项。',
      en: 'Turns research into source-backed risk and catalyst monitoring with thresholds and review cadence.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'monitoring', 'risk'],
    riskNote: {
      zh: '冷启动实验；不负责估值或交易决策。',
      en: 'Cold-start experiment; it does not make valuation or trading decisions.',
    },
  },
  {
    key: 'valuationInvestmentStrategy',
    name: 'valuation-investment-strategy',
    label: { zh: '估值与情景分析', en: 'Valuation Investment Strategy' },
    description: {
      zh: '在事实基础完成后构建带假设、情景和失效条件的估值框架。',
      en: 'Builds valuation scenarios with assumptions and invalidation conditions after the factual base is ready.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'risk', 'valuation'],
    riskNote: {
      zh: '冷启动实验；输出不等于买卖或仓位建议。',
      en: 'Cold-start experiment; output is not a buy, sell, or position-size recommendation.',
    },
  },
  {
    key: 'strategyBusinessTransition',
    name: 'strategy-business-transition',
    label: { zh: '战略与业务转型', en: 'Strategy Business Transition' },
    description: {
      zh: '检验公司战略叙事、业务迁移、资本配置和转型里程碑。',
      en: 'Tests strategy narratives, business migration, capital allocation, and transition milestones.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'strategy', 'risk'],
    riskNote: {
      zh: '冷启动实验；不负责估值或交易计划。',
      en: 'Cold-start experiment; it does not make valuation or trading plans.',
    },
  },
  {
    key: 'industryCompetitionMoat',
    name: 'industry-competition-moat',
    label: { zh: '行业竞争与护城河', en: 'Industry Competition Moat' },
    description: {
      zh: '分析行业结构、竞争格局、供需和公司差异化是否可持续。',
      en: 'Analyzes industry structure, competition, supply-demand, and sustainable differentiation.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'business-analysis', 'competition', 'risk'],
    riskNote: {
      zh: '冷启动实验；行业判断仍需回到公开证据。',
      en: 'Cold-start experiment; industry conclusions still require public evidence.',
    },
  },
  {
    key: 'businessDecompositionOrderQuality',
    name: 'business-decomposition-order-quality',
    label: { zh: '业务拆解与订单质量', en: 'Business Decomposition Order Quality' },
    description: {
      zh: '拆解产品、客户、项目和订单，检查增长能否转化为收入和现金。',
      en: 'Breaks down products, customers, projects, and orders to test conversion into revenue and cash.',
    },
    owner: 'spikeHongg',
    repository: 'china-stock-research-skills',
    status: 'watchlist',
    lastCommit: '2026-03-09',
    reviewBy: '2026-11-06',
    tags: ['a-share', 'business-analysis', 'cash-flow', 'orders', 'risk'],
    riskNote: {
      zh: '冷启动实验；不负责最终估值或买卖建议。',
      en: 'Cold-start experiment; it does not make final valuation or trading recommendations.',
    },
  },
])

export const SELECTED_SKILL_TAG_LABELS = Object.freeze({
  zh: {
    all: '全部',
    'a-share': 'A 股',
    'business-analysis': '业务分析',
    'cash-flow': '现金流',
    competition: '竞争格局',
    'financial-health': '财务健康',
    monitoring: '监控',
    orders: '订单',
    perspective: '分析视角',
    risk: '风险',
    strategy: '战略',
    valuation: '估值',
  },
  en: {
    all: 'All',
    'a-share': 'A-share',
    'business-analysis': 'Business analysis',
    'cash-flow': 'Cash flow',
    competition: 'Competition',
    'financial-health': 'Financial health',
    monitoring: 'Monitoring',
    orders: 'Orders',
    perspective: 'Perspective',
    risk: 'Risk',
    strategy: 'Strategy',
    valuation: 'Valuation',
  },
})
